import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  scroll: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  loadingText: { color: "#fff", fontSize: 16, marginTop: 8 },
  errorEmoji: { fontSize: 48 },
  errorTitle: { color: "#fff", fontSize: 20, fontWeight: "700" },
  errorMessage: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 14,
    textAlign: "center",
    paddingHorizontal: 32,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 24,
  },
  locationPin: { fontSize: 18 },
  city: { color: "#fff", fontSize: 22, fontWeight: "700" },
  region: { color: "rgba(255,255,255,0.7)", fontSize: 13 },
  mainWeather: { alignItems: "center", marginBottom: 28 },
  weatherEmoji: { fontSize: 80, marginBottom: 8 },
  temperature: { color: "#fff", fontSize: 80, fontWeight: "200", lineHeight: 88 },
  condition: { color: "#fff", fontSize: 22, fontWeight: "600", marginTop: 4 },
  feelsLike: { color: "rgba(255,255,255,0.7)", fontSize: 14, marginTop: 4 },
  pillRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 28,
    gap: 8,
  },
  pill: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  pillValue: { color: "#fff", fontSize: 16, fontWeight: "700" },
  pillLabel: { color: "rgba(255,255,255,0.65)", fontSize: 11, marginTop: 2 },
  section: { marginBottom: 28 },
  sectionTitle: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  forecastRow: { gap: 8, paddingRight: 4 },
  credit: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 11,
    textAlign: "center",
    marginTop: 4,
  },
  searchRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    color: "#fff",
    fontSize: 15,
  },
  searchButton: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  searchButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  searchError: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 14,
    marginBottom: 12,
  },
});
